### ISSUE TITLE
Fix links to mashape.com

### ISSUE THREAD

**Issue by overmanager** [semanticanalyzer/nlproc_sdk_sample_code#4]
The API is not available at [https://market.mashape.com/dmitrykey/russiansentimentanalyzer](market.mashape.com/dmitrykey/russiansentimentanalyzer). 
The correct link — https://rapidapi.com/insider-insider-default/api/russiansentimentanalyzer

**Comment by DmitryKey** [comment]
hey @overmanager thanks for reporting the issue! I have fixed the README. Code changes coming shortly.
